[package]
name = "quill"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
dirs = "6.0.0"
shared = { path = "../shared", features = ["interpreter"]}
